# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateBitcoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(max_length=256)),
                ('public_key_address', models.CharField(max_length=256)),
                ('private_key_address', models.CharField(max_length=256)),
            ],
        ),
    ]
