# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_app', '0002_auto_20180716_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
