# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_app', '0003_transferamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferamount',
            old_name='amount',
            new_name='amount_field',
        ),
        migrations.AddField(
            model_name='transferamount',
            name='from_address',
            field=models.CharField(default=514222, max_length=256),
            preserve_default=False,
        ),
    ]
