# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_app', '0004_auto_20180717_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferamount',
            name='amount_field',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
